apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: lab03
data:
  web.conf: |
    server {
    listen       80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /protected {
      auth_basic           "Administrator’s Area";
      auth_basic_user_file /etc/nginx/secret/htpasswd;
      try_files SUCCESS @return200;
    }

    location @return200 {
      return 200 'SECRET MESSAGE!!!';
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
    }
  app1.html: |
    <h1>Hello from Web 1 </h1>
  app2.html: |
    <h1>Hello from Web 2</h1>
